# Generated by Django 6.1 on 2026-08-24 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                default="000000000000",
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 12 digits.",
                        regex="^\\d{12}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
