# Generated by Django 6.1 on 2026-08-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employee",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
