# Generated by Django 6.1 on 2026-08-25 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_employee_failed_login_attempts_employee_locked_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 12 digits.",
                        regex="^\\d{12}$",
                    )
                ],
            ),
        ),
    ]
