# Generated by Django 6.1 on 2026-08-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_employee_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
