# Generated by Django 6.1 on 2026-08-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="auto_punched_out",
            field=models.BooleanField(default=False),
        ),
    ]
