# Generated by Django 6.0.8 on 2026-09-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_attendance_auto_punched_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="break_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="break_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
