# Generated by Django 6.0.8 on 2026-09-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_attendance_break_in_attendance_break_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="total_timing",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
