# Generated by Django 6.0.8 on 2026-09-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_attendance_total_timing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="break_in",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="break_out",
        ),
        migrations.CreateModel(
            name="Break",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("break_in", models.DateTimeField()),
                ("break_out", models.DateTimeField(blank=True, null=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="user.attendance",
                    ),
                ),
            ],
        ),
    ]
