# Generated by Django 6.0.8 on 2026-09-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_remove_attendance_break_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="breaks",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name="Break",
        ),
    ]
