# Generated by Django 6.0.8 on 2026-09-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_attendance_breaks_delete_break"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="breaks",
            new_name="break_in",
        ),
        migrations.AddField(
            model_name="attendance",
            name="break_out",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
